# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_SlatorKoster')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_SlatorKoster')
    _SlatorKoster = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SlatorKoster', [dirname(__file__)])
        except ImportError:
            import _SlatorKoster
            return _SlatorKoster
        try:
            _mod = imp.load_module('_SlatorKoster', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _SlatorKoster = swig_import_helper()
    del swig_import_helper
else:
    import _SlatorKoster
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SlatorKoster(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SlatorKoster, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SlatorKoster, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _SlatorKoster.new_SlatorKoster()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _SlatorKoster.delete_SlatorKoster
    __del__ = lambda self: None

    def setParameter(self, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11):
        return _SlatorKoster.SlatorKoster_setParameter(self, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)

    def V_pppi(self, r):
        return _SlatorKoster.SlatorKoster_V_pppi(self, r)

    def V_ppsigma(self, r):
        return _SlatorKoster.SlatorKoster_V_ppsigma(self, r)

    def V_pdpi(self, r):
        return _SlatorKoster.SlatorKoster_V_pdpi(self, r)

    def V_pdsigma(self, r):
        return _SlatorKoster.SlatorKoster_V_pdsigma(self, r)

    def E_xz(self, r, l, n):
        return _SlatorKoster.SlatorKoster_E_xz(self, r, l, n)

    def E_zz(self, r, n):
        return _SlatorKoster.SlatorKoster_E_zz(self, r, n)

    def E_z_xz(self, r, l, n):
        return _SlatorKoster.SlatorKoster_E_z_xz(self, r, l, n)

    def E_z_xy(self, r, l, m, n):
        return _SlatorKoster.SlatorKoster_E_z_xy(self, r, l, m, n)

    def E_z_x2y2(self, r, l, m, n):
        return _SlatorKoster.SlatorKoster_E_z_x2y2(self, r, l, m, n)

    def E_z_z2(self, r, l, m, n):
        return _SlatorKoster.SlatorKoster_E_z_z2(self, r, l, m, n)

    def ft_E_xz(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_xz(self, kx, ky)

    def ft_E_yz(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_yz(self, kx, ky)

    def ft_E_zz(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_zz(self, kx, ky)

    def ft_E_zz2(self, kx, ky, V_pppi0=-2.7, V_ppsigma0=0.48, a0=1.42, d0=3.35, delta0=0.45264, d=0.45255):
        return _SlatorKoster.SlatorKoster_ft_E_zz2(self, kx, ky, V_pppi0, V_ppsigma0, a0, d0, delta0, d)

    def ft_E_z_xz(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_z_xz(self, kx, ky)

    def ft_E_z_yz(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_z_yz(self, kx, ky)

    def ft_E_z_xy(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_z_xy(self, kx, ky)

    def ft_E_z_x2y2(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_z_x2y2(self, kx, ky)

    def ft_E_z_z2(self, kx, ky):
        return _SlatorKoster.SlatorKoster_ft_E_z_z2(self, kx, ky)

    def setIntegrateRegion(self, xMin, xMax, yMin, yMax):
        return _SlatorKoster.SlatorKoster_setIntegrateRegion(self, xMin, xMax, yMin, yMax)

    def setIntegrateInterval(self, m, n):
        return _SlatorKoster.SlatorKoster_setIntegrateInterval(self, m, n)
SlatorKoster_swigregister = _SlatorKoster.SlatorKoster_swigregister
SlatorKoster_swigregister(SlatorKoster)

# This file is compatible with both classic and new-style classes.


